sudo: false
language: node_js
node_js:
  - 'stable'
  - '6'
  - '5'
matrix:
  fast_finish: true
script: npm run coveralls
before_deploy: npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
